### ISSUE TITLE
Compile protobuf for WASM

### ISSUE THREAD

**Issue by nsourligas** [juangburgos/ProtobufTests#1]
Hi,

It's great to see a WASM example using protobuf! But how did you manage to compile the WASM client in Linux? 

Because I am currently trying to do the same thing but so far I wasn't able to make it happen. Could you briefly explain what steps you followed to achieve this?

**Comment by juangburgos** [comment]
This was a long time ago, so I don't know if I am remembering correctly, but I believe I built it using this docker image:
* https://github.com/mauricek/qtwasm_builder

I also used this post as a reference

* https://www.qt.io/blog/2019/03/05/using-docker-test-qt-webassembly

I built the protobuf libraries to wasm with something like:
```shell
CC=emcc CXX=em++ cmake .. -Dprotobuf_BUILD_SHARED_LIBS=OFF
emmake make gmock libprotoc libprotobuf-lite gmock_main
```
And then built the gui client from this repo with something like:
```shell
qmake ../source/tests/03_gui_client/
emmake make all
```

**Comment by nsourligas** [comment]
@juangburgos  thank you for your prompt reply and I appreciate for sharing all the information!

I will try to follow the same procedure and see if it works for me too.
